INSERT INTO "user"(user_username, user_password) VALUES ('demo_username', '32d5f9c281a2cfc1f3733e3aca2bad1f7d46c152aa8851f967c53539d301abdb');
INSERT INTO album(album_id, album_name, album_author) VALUES (351, 'Minecraft - Volume Alpha', 'C418');
INSERT INTO album(album_id, album_name, album_author) VALUES (495, 'Minecraft - Volume Beta', 'C418');
INSERT INTO album(album_id, album_name, album_author) VALUES (837, 'DOOM 2016 Soundtrack', 'Mick Gordon');

INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Key', 65);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Door', 111);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Subwoofer Lullaby', 208);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Death', 41);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Living Mice', 177);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Moog City', 160);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Haggstorm', 204);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Minecraft', 254);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Oxygène', 65);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Équinoxe', 114);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Mice on Venus', 281);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Dry Hands', 68);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Wet Hands', 90);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Clark', 191);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Chris', 87);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Thriteen', 176);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Excuse', 124);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Sweden', 215);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Cat', 186);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Dog', 145);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Danny', 254);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Beginning', 102);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Droopy likes ricochet', 96);
INSERT INTO song(album_id, song_name, song_length) VALUES (351, 'Droopy likes your face', 116);


INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Ki', 92);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Alpha', 603);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Dead Voxel', 296);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Blind Spots', 332);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Flake', 170);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Moog City 2', 180);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Concrete Halls', 254);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Biome Fest', 578);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Mutation', 185);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Haunt Muskie', 361);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Warmth', 239);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Floating Trees', 244);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Aria Math', 310);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Kyoto', 249);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Ballad of the Cats', 275);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Taswell', 515);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Beginning 2', 176);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Dreiton', 497);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'The End', 904);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Chirp', 187);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Wait', 234);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Mellohi', 98);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Stal', 152);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Strad', 188);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Eleven', 71);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Ward', 250);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Mall', 198);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Blocks', 343);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Far', 192);
INSERT INTO song(album_id, song_name, song_length) VALUES (495, 'Intro', 276);